USE master;
GO
ALTER DATABASE [DB NAME]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO


-- ALTER DATABASE [db_name] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

-- ALTER DATABASE [db_name] SET MULTI_USER WITH ROLLBACK IMMEDIATE

-- ALTER DATABASE [db_name] SET OFFLINE WITH ROLLBACK IMMEDIATE

-- EXEC sp_who2